### ISSUE TITLE
Spectabis crashes when unable to find game on GiantBomb

### ISSUE THREAD

**Issue by Teslahaha** [FaithLV/Spectabis#24]
I am using the GiantBomb API to add games into Spectabis.
When trying to add a game whose name does not appear in the GiantBomb database, Spectabis crashes.

For example, when adding the ISO AutoModellista, Spectabis crashed because that exact name couldn't be found on GiantBomb; it was missing a space. When renaming the ISO to Auto Modellista, the app didn't crash and was able to find it.

**Comment by CyberFoxHax** [comment]
it's an old issue but i tested on a blank .iso file called AutoModellista
i got this result in the application. I was not using GiantBomb, but it also didn't crash.
![image](https://user-images.githubusercontent.com/7734690/59498167-74292380-8ec7-11e9-8247-36df0614a64a.png)

Can we confirm this bug does no longer exist?
