### ISSUE TITLE
Downloading Boxart

### ISSUE THREAD

**Issue by viceless** [FaithLV/Spectabis#49]
Program says 'downloading boxart' endlessly on the latest build for me

**Comment by easysoft-mobility** [comment]
Same with me

**Comment by andrewjmetzger** [comment]
Chiming in here to say that this issue exists under Spectabis v1.10 while using the GiantBomb and IGDB APIs. 

The OpenGameDB API is defunct. I will test more APIs and report the results.

For now, the only workaround I know of is to manually download and add the boxart to a game entry in Spectabis.

**Comment by andrewjmetzger** [comment]
@viceless You need to set any API key (in Spectabis' settings) for boxart fetching to work, but it seems that Spectabis is having issues using the APIs anyway.

**Comment by grantfar** [comment]
I fixed this in my pull request.

**Comment by andrewjmetzger** [comment]
> I fixed this in my pull request.

#50 (naming the PR for reference)
