### ISSUE TITLE
Picks the wrong language for its config

### ISSUE THREAD

**Issue by RedDevilus** [FaithLV/Spectabis#57]
I have tested it extensively with stable and dev builds:
Set everything to locale English for Windows and the PCSX2 versions
Then put games into Spectabis and it always gives me Arabic as standard PCSX2 locale.

I dont even use Arabic anywhere. 

Is this the culprit?
![image](https://user-images.githubusercontent.com/24227051/81476076-210f3c00-9210-11ea-8f08-25e144904803.png)

**Comment by FaithLV** [comment]
First hearing of this, very strange.

What is that file you're referencing?

@CyberFoxHax Any ideas here?

**Comment by RedDevilus** [comment]
Just adding that the picture is from the last line from PCSX2_ui.ini (config from any game). Not sure how thats happened.

**Comment by FaithLV** [comment]
Yeah, I don't have anything `UTF-8` releated under Linux.

**Comment by RedDevilus** [comment]
Its a Windows 10 problem i think. I went into 1.4 to 1.7 (system default and other times especially choosing English U.S.) and without Spectabis it will go into English. If i drag and drop then open configurator then it displays in Arabic. Very strange indeed.

**Comment by CyberFoxHax** [comment]
I think a lot of applications has a tendency to pick Arabic because when sorted alphabetically it's the first one on the list. Seeing how the value is set to -1 or blank it seems to instead of picking the right one, it just picks the first one.

How long have you had this problem?

**Comment by RedDevilus** [comment]
From what i remember it started around last week. But i havent been using spectabis because having no time to use it. The windows installation is around 1-2 months by now. I'm not sure how this happened. First time ive seen it do that. Like Cyber says from what spectabis does is do -1 on the language which picks the first language but from where?

**Comment by RedDevilus** [comment]
I did some more research: System locale is correct , region and more are also fine. However i reinstalled CrystalDiskInfo again to check if there is a problem and there and low and behold the language is polish which is the first language of the 2nd list.

**Comment by RedDevilus** [comment]
Closing this due to a Windows problems that has been fixed with reinstalling. Thanks anyway
